version: '3'
services:
 # php,apacheのコンテナ
 app:
   ports:
     - "80:80"
   build: ./docker/app
   container_name: laravel_app
   volumes:
     - ./src:/var/www/html
 # MySQLコンテナ
 db:
   image: mysql:5.7
   container_name: laravel_db
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: laravel_db
     MYSQL_USER: root
     MYSQL_PASSWORD: password
     TZ: 'Asia/Tokyo'
   # 起動時のコマンド
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
     - ./docker/db/sql:/docker-entrypoint-initdb.d
   ports:
     - 3306:3306