version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:8.0.18
    environment:
      - DB_CONNECTION: testing

    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update
      # - run:
          # name: docker-compose build
          # command: cd laradock && sudo docker-compose build workspace

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "./myProject/composer.json" }}
      #       - v1-dependencies-

      - run:
          name: composer
          command: |
            cd laradock && \
            sudo docker-compose exec workspace composer require --dev phpunit/phpunit ^7.0

      # - save_cache:
      #     paths:
      #       - ./myProject/vendor
      #     key: v1-dependencies-{{ checksum "./myProject/composer.json" }}
      
      # - run: ls -lR
      - run:
          name: UnitTest
          command: cd myProject && vendor/bin/phpunit