version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up build
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run: docker-compose run --workdir="/var/www/html/laravelapp" app composer install
      - run:
          name: DB-setup
          command: |
            docker-compose run --workdir="/var/www/html/laravelapp" app php artisan migrate:refresh --force --database=testing
            docker-compose run --workdir="/var/www/html/laravelapp" app php artisan db:seed --database=testing
      - run:
          name: test
          command: |
            docker-compose run --workdir="/var/www/html/laravelapp" app vendor/bin/phpunit
      - run:
          name: docker-compose down
          command: docker-compose down