version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:edge
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose up build
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: docker-compose stop
          command: |
            set -x
            docker-compose stop
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run: docker-compose run --workdir="/var/www/html/laravelapp" app composer install
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Create Database
          command: mysql  -h 127.0.0.1 -u root -e "create database test;"
      - run:
          name: DB-migrate
          command: |
            docker-compose run --workdir="/var/www/html/laravelapp" app php artisan migrate:refresh --force --database=testing
            docker-compose run --workdir="/var/www/html/laravelapp" app php artisan db:seed --database=testing
      - run:
          name: test
          command: |
            docker-compose run --workdir="/var/www/html/laravelapp" app vendor/bin/phpunit
      - run:
          name: docker-compose down
          command: docker-compose down