version: 2.1
executors:
  my-executor:
    machine:
      image: circleci/classic:edge
jobs:
  build_test:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: docker-compose stop down
          command: |
            set -x
            docker-compose stop && docker-compose down
      - run:
          name: docker-compose up build
          command: |
            set -x
            docker-compose up --build -d
      - run:
          name: docker-compose up
          command: |
            set -x
            docker-compose up -d
      - run: 
          name: install composer
          command: docker-compose run --workdir="/var/www/html/laravelapp" app composer install
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      # - run:
      #     name: Wait For DB
      #     command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Create Database for test
          working_directory: laravelapp
          command: docker-compose exec db mysql -u root -proot -e "create database test;"
      - run:
          name: DB-migrate
          command: |
            docker-compose run --workdir="/var/www/html/laravelapp" app php artisan migrate:refresh --force --env=testing
            docker-compose run --workdir="/var/www/html/laravelapp" app php artisan db:seed --env=testing
      - run:
          name: RUN phpunit
          command: |
            docker-compose run --workdir="/var/www/html/laravelapp" app vendor/bin/phpunit
      - run:
          name: docker-compose down
          command: docker-compose down
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: deploy by ssh
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ~/phpP_work && git pull origin develop && echo $ENV_FILE | base64 -di > ~/phpP_work/src/laravelapp/.env"
      - run:
          name: restart docker by ssh
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ~/phpP_work && docker-compose stop && docker-compose down && docker-compose up -d app"
      - run:
          name: migrate-DB by ssh
          command: |
            ssh $SSH_USER@$SSH_HOST "cd ~/phpP_work && docker-compose run --workdir="/var/www/html/laravelapp" app php artisan migrate"
workflows:
  version: 2.1
  workflow:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only: 
                - master
