<?php

use Illuminate\Database\Seeder;

class ReviewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reviews')->insert([
            [
                'user_name' =>'ippan',
                'genre' => '0',
                'title' =>'こころ',
                'chysh' =>'夏目漱石',
                'hyk' =>'5',
                'review_niy' =>'初回は高校の授業で読んで、退屈だと感じた。再度読むと引き込まれた。話し言葉で書かれていて、読みやすい。また読みたい思う',
                'reread_times' => '3',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => '2019/09/10',
                'read_end_date_for_third' => '2020/03/20',
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'ippan',
                'genre' => '0',
                'title' =>'人間失格',
                'chysh' =>'太宰治',
                'hyk' =>'5',
                'review_niy' =>'タイトルに惹かれ読み始めはまった',
                'reread_times' => '1',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => NULL,
                'read_end_date_for_third' => NULL,
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'ippan',
                'genre' => '1',
                'title' =>'エンタメの夜明け',
                'chysh' =>'馬場やすお',
                'hyk' =>'5',
                'review_niy' =>'名作の中の名作。他の人にもぜひ勧めたい',
                'reread_times' => '1',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => NULL,
                'read_end_date_for_third' => NULL,
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'ippan',
                'genre' => '2',
                'title' =>'社会心理学',
                'chysh' =>'亀田たろう',
                'hyk' =>'2',
                'review_niy' =>'あまり面白いと思えなかった。',
                'reread_times' => '1',
                'read_end_date_for_first' => '2018/02/01',
                'read_end_date_for_second' => NULL,
                'read_end_date_for_third' => NULL,
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'ippan',
                'genre' => '3',
                'title' =>'ドラえもん',
                'chysh' =>'藤子不二雄',
                'hyk' =>'4',
                'review_niy' =>'期待を裏切らない！！',
                'reread_times' => '4',
                'read_end_date_for_first' => '2021/01/01',
                'read_end_date_for_second' => '2019/09/10',
                'read_end_date_for_third' => '2020/03/20',
                'read_end_date_for_fourth' => '2021/01/11',
            ],
            [
                'user_name' =>'ippan',
                'genre' => '8',
                'title' =>'旅行紀行',
                'chysh' =>'三島由紀夫',
                'hyk' =>'5',
                'review_niy' =>'はじめてよんだ旅行記。自粛時期でなかなか出かけれ慣れなかったので読めて旅行した気分になれてよかった',
                'reread_times' => '3',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => NULL,
                'read_end_date_for_third' => NULL,
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'ippan',
                'genre' => '8',
                'title' =>'小説読本',
                'chysh' =>'三島由紀夫',
                'hyk' =>'5',
                'review_niy' =>'「小説とは何か。」について真正面から考えてかかれている',
                'reread_times' => '3',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => '2019/09/10',
                'read_end_date_for_third' => '2020/03/20',
                'read_end_date_for_fourth' => NULL,
            ],
//  searchtest用
            [
                'user_name' =>'jiro',
                'genre' => '0',
                'title' =>'T文学・評論',
                'chysh' =>'C文学・評論',
                'hyk' =>'5',
                'review_niy' =>'よかった',
                'reread_times' => '3',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => '2019/09/10',
                'read_end_date_for_third' => '2020/03/20',
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'jiro',
                'genre' => '1',
                'title' =>'Tノンフィクション',
                'chysh' =>'Cノンフィクション',
                'hyk' =>'5',
                'review_niy' =>'よかった',
                'reread_times' => '3',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => '2019/09/10',
                'read_end_date_for_third' => '2020/03/20',
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'jiro',
                'genre' => '2',
                'title' =>'T人文・思想・宗教',
                'chysh' =>'C人文・思想・宗教',
                'hyk' =>'5',
                'review_niy' =>'よかった',
                'reread_times' => '3',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => '2019/09/10',
                'read_end_date_for_third' => '2020/03/20',
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'jiro',
                'genre' => '3',
                'title' =>'Tコミックス',
                'chysh' =>'Cコミックス',
                'hyk' =>'5',
                'review_niy' =>'よかった',
                'reread_times' => '3',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => '2019/09/10',
                'read_end_date_for_third' => '2020/03/20',
                'read_end_date_for_fourth' => NULL,
            ],
            [
                'user_name' =>'jiro',
                'genre' => '8',
                'title' =>'Tその他',
                'chysh' =>'Cその他',
                'hyk' =>'5',
                'review_niy' =>'よかった',
                'reread_times' => '3',
                'read_end_date_for_first' => '2019/01/01',
                'read_end_date_for_second' => '2019/09/10',
                'read_end_date_for_third' => '2020/03/20',
                'read_end_date_for_fourth' => NULL,
            ],
            
        ]);
        factory(App\Review::class, 10)->create();
    }
}
